import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'index',
    'samples',
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: true,
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: '01-introduction'},
        {type: 'autogenerated', dirName: '02-getting-started'},
      ],
    },
    {
      type: 'category',
      label: 'Core Language',
      collapsible: true,
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: '03-object-oriented'},
        {type: 'autogenerated', dirName: '04-error-handling'},
        {type: 'autogenerated', dirName: '05-strings-and-numbers'},
        {type: 'autogenerated', dirName: '06-collections'},
      ],
    },
    {
      type: 'category',
      label: 'Data and Applications',
      collapsible: true,
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: '07-file-io'},
        {type: 'autogenerated', dirName: '08-database-sql'},
        {type: 'autogenerated', dirName: '09-java-interop'},
        {type: 'autogenerated', dirName: '10-event-handling'},
      ],
    },
    {
      type: 'category',
      label: 'Tools and Web',
      collapsible: true,
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: '11-debugging'},
        {type: 'autogenerated', dirName: '12-web-development'},
      ],
    },
  ],
};

export default sidebars;
